class CfgWhitelists {
    class Kasrkin {
        items[] = {"TIOW_CadianHellgun","IC_Launcher_AT_grey","TIOW_Bolt_Pistol","TIOW_Bolt_Pistol2","ic_cad_laspistol","ic_hellgun_optic","ic_las_optic_2x","TIOW_2x4xScope_1","IC_bayonet_01","TIOW_CadianHellgun_Mag","ic_hellgun_mag","ic_PlasmaGunRed","TIOW_IG_Flamer","ic_cad_melta","IC_Krak_rocket_mag","IC_krakk_Missile_mag","ic_melta_canister","TIOW_IGBoltPistol_Mag","ic_laspistol_powerpack","ic_plasma_canisterRed","TIOW_Krieg_Flamer_mag","IC_cad_kasr_helmet_beige","IC_cad_kasr_helmet_green","IC_CAD_KasrArmor_beige","IC_CAD_KasrArmor_green","IC_CAD_U_776_B","IC_CAD_kasr_pack_beige","IC_CAD_kasr_pack_green","IC_CAD_kasr_pack_green_02","ic_cad_Goggles","ic_cad_magnoculars","WBK_Narth_3","ItemMap","ItemCompass","TFAR_anprc152","TFAR_rf7800str","ACE_Altimeter","ItemGPS","DSA_Detector","IC_CAD_FRAG_mag","IC_CAD_KRAK_mag","IC_CAD_KRAKV2_mag","IC_CAD_SMOKE_mag","Chemlight_blue","Chemlight_green","IC_CAD_CHARGE_placeable_mag","ACE_adenosine","ACE_RangeTable_82mm","ACE_artilleryTable","DSA_Antidote","ACE_fieldDressing","ACE_elasticBandage","ACE_packingBandage","ACE_quikclot","ACE_bloodIV","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bodyBag","ACE_CableTie","ACE_DefusalKit","ACE_EarPlugs","ACE_EntrenchingTool","ACE_epinephrine","FirstAidKit","ACE_Flashlight_MX991","ACE_IR_Strobe_Item","ACE_M26_Clacker","Medikit","MineDetector","ACE_morphine","ACE_plasmaIV","ACE_plasmaIV_250","ACE_plasmaIV_500","ACE_RangeCard","ACE_salineIV","ACE_salineIV_250","ACE_salineIV_500","ACE_splint","ACE_surgicalKit","ToolKit","ACE_tourniquet","ACE_UAVBattery","ACE_wirecutter","ACE_SpraypaintBlue","ACE_SpraypaintGreen","ACE_SpraypaintRed","ACE_SpareBarrel","IC_CAD_U_836_B","IC_CAD_kasr_pack_beige_02","IC_Frag_rocket_mag","IC_frag_Missile_mag","dm_KantraelMaskGreen","IC_cad_rebreather_beige","IC_cad_rebreather_green"};
    };
    class Scions {
        items[] = {"IC_Hellgun","IC_Launcher_AA_grey","IC_Launcher_AT_grey","ic_cad_laspistol","ic_hellgun_optic","acc_pointer_IR","acc_flashlight","IC_krakk_Missile_mag","IC_Flak_Missile_mag","ic_laspistol_powerpack","ic_hellgun_mag","IC_frag_Missile_mag","ic_hellgun_mag2","IC_scion_helm_BASE","IC_scion_beret","IC_Scion_U_B","IC_Scion_armor_01","IC_Scion_Powerpack_01","IC_Scion_mask_01","IC_Scion_mask_02","IC_Scion_mask_03","TIOW_IG_NVG_Green","ic_cad_magnoculars","ItemMap","ItemCompass","TFAR_anprc152","TFAR_rf7800str","ACE_Altimeter","ItemGPS","IC_CAD_FRAG_mag","IC_CAD_KRAK_mag","IC_CAD_KRAKV2_mag","IC_CAD_SMOKE_mag","Chemlight_blue","Chemlight_green","SmokeShell","TIOW_ig_smoke_grenade_mag","TIOW_ig_melta_bomb_mag","IC_CAD_CHARGE_placeable_mag","ACE_RangeTable_82mm","ACE_adenosine","ACE_artilleryTable","ACE_fieldDressing","ACE_elasticBandage","ACE_packingBandage","ACE_quikclot","ACE_bloodIV","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bodyBag","ACE_CableTie","ACE_DefusalKit","ACE_EarPlugs","ACE_EntrenchingTool","ACE_epinephrine","ACE_Flashlight_MX991","FirstAidKit","ACE_IR_Strobe_Item","ACE_M26_Clacker","Medikit","MineDetector","ACE_morphine","ACE_plasmaIV","ACE_plasmaIV_250","ACE_plasmaIV_500","ACE_RangeCard","ACE_salineIV","ACE_salineIV_250","ACE_salineIV_500","ACE_SpareBarrel","ACE_splint","ACE_surgicalKit","ToolKit","ACE_tourniquet","ACE_UAVBattery","ACE_wirecutter"};
    };
    class Mission {
        items[] = {"Item7", "Item8", "Item9"};
    };
};